# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import daq_service_pb2 as daq__service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in daq_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DAQServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartStreaming = channel.unary_unary(
                '/daq.DAQService/StartStreaming',
                request_serializer=daq__service__pb2.StreamingRequest.SerializeToString,
                response_deserializer=daq__service__pb2.StreamingResponse.FromString,
                _registered_method=True)
        self.StopStreaming = channel.unary_unary(
                '/daq.DAQService/StopStreaming',
                request_serializer=daq__service__pb2.StopRequest.SerializeToString,
                response_deserializer=daq__service__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetStreamingStatus = channel.unary_unary(
                '/daq.DAQService/GetStreamingStatus',
                request_serializer=daq__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=daq__service__pb2.StreamingStatusResponse.FromString,
                _registered_method=True)
        self.ConnectToStream = channel.unary_unary(
                '/daq.DAQService/ConnectToStream',
                request_serializer=daq__service__pb2.ConnectRequest.SerializeToString,
                response_deserializer=daq__service__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.DisconnectFromStream = channel.unary_unary(
                '/daq.DAQService/DisconnectFromStream',
                request_serializer=daq__service__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=daq__service__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.GetAvailableSensors = channel.unary_unary(
                '/daq.DAQService/GetAvailableSensors',
                request_serializer=daq__service__pb2.SensorsRequest.SerializeToString,
                response_deserializer=daq__service__pb2.AvailableSensorsResponse.FromString,
                _registered_method=True)
        self.GetAvailableVideo = channel.unary_unary(
                '/daq.DAQService/GetAvailableVideo',
                request_serializer=daq__service__pb2.VideoRequest.SerializeToString,
                response_deserializer=daq__service__pb2.AvailableVideoResponse.FromString,
                _registered_method=True)
        self.StreamSensorData = channel.unary_stream(
                '/daq.DAQService/StreamSensorData',
                request_serializer=daq__service__pb2.StreamRequest.SerializeToString,
                response_deserializer=daq__service__pb2.SensorData.FromString,
                _registered_method=True)
        self.StreamVideo = channel.unary_stream(
                '/daq.DAQService/StreamVideo',
                request_serializer=daq__service__pb2.VideoRequest.SerializeToString,
                response_deserializer=daq__service__pb2.VideoFrame.FromString,
                _registered_method=True)
        self.StreamAudio = channel.unary_stream(
                '/daq.DAQService/StreamAudio',
                request_serializer=daq__service__pb2.AudioRequest.SerializeToString,
                response_deserializer=daq__service__pb2.AudioFrame.FromString,
                _registered_method=True)
        self.StreamCombinedData = channel.unary_stream(
                '/daq.DAQService/StreamCombinedData',
                request_serializer=daq__service__pb2.CombinedRequest.SerializeToString,
                response_deserializer=daq__service__pb2.CombinedData.FromString,
                _registered_method=True)
        self.SendRemoteCommand = channel.unary_unary(
                '/daq.DAQService/SendRemoteCommand',
                request_serializer=daq__service__pb2.RemoteCommand.SerializeToString,
                response_deserializer=daq__service__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.RequestRemoteControl = channel.unary_unary(
                '/daq.DAQService/RequestRemoteControl',
                request_serializer=daq__service__pb2.ControlRequest.SerializeToString,
                response_deserializer=daq__service__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.Authenticate = channel.unary_unary(
                '/daq.DAQService/Authenticate',
                request_serializer=daq__service__pb2.AuthRequest.SerializeToString,
                response_deserializer=daq__service__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.ValidatePermission = channel.unary_unary(
                '/daq.DAQService/ValidatePermission',
                request_serializer=daq__service__pb2.PermissionRequest.SerializeToString,
                response_deserializer=daq__service__pb2.PermissionResponse.FromString,
                _registered_method=True)


class DAQServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartStreaming(self, request, context):
        """Master functions (data source)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamingStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectToStream(self, request, context):
        """Client functions (stream participants)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectFromStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableSensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSensorData(self, request, context):
        """Streaming endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCombinedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRemoteCommand(self, request, context):
        """Remote control (with security)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRemoteControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Authenticate(self, request, context):
        """Authentication & security
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DAQServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStreaming,
                    request_deserializer=daq__service__pb2.StreamingRequest.FromString,
                    response_serializer=daq__service__pb2.StreamingResponse.SerializeToString,
            ),
            'StopStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStreaming,
                    request_deserializer=daq__service__pb2.StopRequest.FromString,
                    response_serializer=daq__service__pb2.StopResponse.SerializeToString,
            ),
            'GetStreamingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamingStatus,
                    request_deserializer=daq__service__pb2.StatusRequest.FromString,
                    response_serializer=daq__service__pb2.StreamingStatusResponse.SerializeToString,
            ),
            'ConnectToStream': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectToStream,
                    request_deserializer=daq__service__pb2.ConnectRequest.FromString,
                    response_serializer=daq__service__pb2.ConnectResponse.SerializeToString,
            ),
            'DisconnectFromStream': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectFromStream,
                    request_deserializer=daq__service__pb2.DisconnectRequest.FromString,
                    response_serializer=daq__service__pb2.DisconnectResponse.SerializeToString,
            ),
            'GetAvailableSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableSensors,
                    request_deserializer=daq__service__pb2.SensorsRequest.FromString,
                    response_serializer=daq__service__pb2.AvailableSensorsResponse.SerializeToString,
            ),
            'GetAvailableVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableVideo,
                    request_deserializer=daq__service__pb2.VideoRequest.FromString,
                    response_serializer=daq__service__pb2.AvailableVideoResponse.SerializeToString,
            ),
            'StreamSensorData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSensorData,
                    request_deserializer=daq__service__pb2.StreamRequest.FromString,
                    response_serializer=daq__service__pb2.SensorData.SerializeToString,
            ),
            'StreamVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=daq__service__pb2.VideoRequest.FromString,
                    response_serializer=daq__service__pb2.VideoFrame.SerializeToString,
            ),
            'StreamAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=daq__service__pb2.AudioRequest.FromString,
                    response_serializer=daq__service__pb2.AudioFrame.SerializeToString,
            ),
            'StreamCombinedData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCombinedData,
                    request_deserializer=daq__service__pb2.CombinedRequest.FromString,
                    response_serializer=daq__service__pb2.CombinedData.SerializeToString,
            ),
            'SendRemoteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRemoteCommand,
                    request_deserializer=daq__service__pb2.RemoteCommand.FromString,
                    response_serializer=daq__service__pb2.CommandResponse.SerializeToString,
            ),
            'RequestRemoteControl': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRemoteControl,
                    request_deserializer=daq__service__pb2.ControlRequest.FromString,
                    response_serializer=daq__service__pb2.ControlResponse.SerializeToString,
            ),
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=daq__service__pb2.AuthRequest.FromString,
                    response_serializer=daq__service__pb2.AuthResponse.SerializeToString,
            ),
            'ValidatePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePermission,
                    request_deserializer=daq__service__pb2.PermissionRequest.FromString,
                    response_serializer=daq__service__pb2.PermissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daq.DAQService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daq.DAQService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DAQService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/StartStreaming',
            daq__service__pb2.StreamingRequest.SerializeToString,
            daq__service__pb2.StreamingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/StopStreaming',
            daq__service__pb2.StopRequest.SerializeToString,
            daq__service__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/GetStreamingStatus',
            daq__service__pb2.StatusRequest.SerializeToString,
            daq__service__pb2.StreamingStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectToStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/ConnectToStream',
            daq__service__pb2.ConnectRequest.SerializeToString,
            daq__service__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectFromStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/DisconnectFromStream',
            daq__service__pb2.DisconnectRequest.SerializeToString,
            daq__service__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/GetAvailableSensors',
            daq__service__pb2.SensorsRequest.SerializeToString,
            daq__service__pb2.AvailableSensorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/GetAvailableVideo',
            daq__service__pb2.VideoRequest.SerializeToString,
            daq__service__pb2.AvailableVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daq.DAQService/StreamSensorData',
            daq__service__pb2.StreamRequest.SerializeToString,
            daq__service__pb2.SensorData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daq.DAQService/StreamVideo',
            daq__service__pb2.VideoRequest.SerializeToString,
            daq__service__pb2.VideoFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daq.DAQService/StreamAudio',
            daq__service__pb2.AudioRequest.SerializeToString,
            daq__service__pb2.AudioFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCombinedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/daq.DAQService/StreamCombinedData',
            daq__service__pb2.CombinedRequest.SerializeToString,
            daq__service__pb2.CombinedData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRemoteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/SendRemoteCommand',
            daq__service__pb2.RemoteCommand.SerializeToString,
            daq__service__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestRemoteControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/RequestRemoteControl',
            daq__service__pb2.ControlRequest.SerializeToString,
            daq__service__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/Authenticate',
            daq__service__pb2.AuthRequest.SerializeToString,
            daq__service__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daq.DAQService/ValidatePermission',
            daq__service__pb2.PermissionRequest.SerializeToString,
            daq__service__pb2.PermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
